drop table employees cascade constraints;
drop table customers cascade constraints;
drop table products cascade constraints;
drop table purchases cascade constraints;
drop table suppliers cascade constraints;
drop table supply cascade constraints;
drop table logs cascade constraints;
drop SEQUENCE pur_seq;
drop SEQUENCE sup_seq;
drop SEQUENCE log_seq;
drop trigger trig_sup;
drop trigger trig_log;
drop trigger trig_pur;